# binsensors.yaml

- platform: ping
  host: 192.168.0.210
  name: system-env

- platform: ping
  host: 192.168.0.157
  name: nodered

- platform: ping
  host: 192.168.0.220
  name: system-west

- platform: ping
  host: 192.168.0.221
  name: system-east

- platform: mqtt
  name: mounts_parked
  state_topic: "mounts/parked"
  payload_on: 0
  payload_off: 1

- platform: mqtt
  name: roof_opened
  state_topic: "roof/opened"
  payload_on: 0
  payload_off: 1

- platform: mqtt
  name: roof_closed
  state_topic: "roof/closed"
  payload_on: 0
  payload_off: 1

- platform: template
  sensors:
    nhs_onbattery:
      friendly_name: "UPS on Battery"
      value_template: "{{ states('sensor.nhs_tensao_entrada') | float < 100 and states('sensor.nhs_tensao_entrada') | float > 135 }}"
      icon_template: 'mdi:power-plug-off'
    nhs_critical:
      friendly_name: "UPS Critical"
      value_template: "{{ not is_state('sensor.nhs_status', 'ok') }}"
      icon_template: 'mdi:battery-20'
    aag_safe:
      friendly_name: "Weather Safe"
      value_template: "{{ is_state('sensor.aag_safe', '1') }}"
      icon_template: 'mdi:weather-night'
    aag_cloudy:
      friendly_name: "Weather Cloudy"
      value_template: "{{ (states('sensor.aag_clouds') | float) >= (states('sensor.aag_sw_clouds') | float) }}"
      icon_template: 'mdi:weather-cloudy'
    aag_rainy:
      friendly_name: "Weather Rainy"
      value_template: "{{ (states('sensor.aag_rain') | float) <= (states('sensor.aag_sw_rain') | float) }}"
      icon_template: 'mdi:weather-pouring'
    aag_light:
      friendly_name: "Weather Light"
      value_template: "{{ (states('sensor.aag_light') | float) <= (states('sensor.aag_sw_light') | float) }}"
      icon_template: 'mdi:lightbulb-on-outline'
    roof_parked:
      friendly_name: "Roof Parked"
      value_template: "{{ is_state('switch.roof_lock', 'on') }}"
      icon_template: 'mdi:lock'
    obs_alert:
      friendly_name: "Alert"
      value_template: "{{ not is_state('sensor.nhs_status', 'ok') or not is_state('sensor.aag_safe', '1') }}"
      icon_template: 'mdi:skull'
    pwr_env:
      friendly_name: "Environment System"
      value_template: "{{ is_state('binary_sensor.system_env', 'on') }}"
      icon_template: 'mdi:power'
    pwr_nodered:
      friendly_name: "Serices Automation"
      value_template: "{{ is_state('binary_sensor.nodered', 'on') }}"
      icon_template: 'mdi:power'
    pwr_east:
      friendly_name: "East System"
      value_template: "{{ is_state('binary_sensor.system_east', 'on') }}"
      icon_template: 'mdi:power'
    pwr_west:
      friendly_name: "West System"
      value_template: "{{ is_state('binary_sensor.system_west', 'on') }}"
      icon_template: 'mdi:power'

