# sensors.yaml

- platform: mqtt
  state_topic: 'hwg/state'
  name: 'hwg_temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.temperatura|round(1) }}'
  icon: "mdi:thermometer"
  force_update: true

- platform: mqtt
  state_topic: 'hwg/state'
  name: 'hwg_humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.umidade|round(1) }}'
  icon: "mdi:water-percent"
  force_update: true



- platform: mqtt
  state_topic: 'aag/state'
  name: 'aag_safe'
  value_template: '{{ value_json.safe }}'
  icon: "mdi:weather-night"
  force_update: true

- platform: mqtt
  state_topic: 'aag/state'
  name: 'aag_clouds'
  value_template: '{{ value_json.clouds }}'
  icon: "mdi:weather-cloudy"
  force_update: true

- platform: mqtt
  state_topic: 'aag/state'
  name: 'aag_sw_clouds'
  value_template: '{{ value_json.sw_clouds }}'
  icon: "mdi:weather-cloudy"
  force_update: true

- platform: mqtt
  state_topic: 'aag/state'
  name: 'aag_rain'
  value_template: '{{ value_json.rain }}'
  icon: "mdi:weather-pouring"
  force_update: true

- platform: mqtt
  state_topic: 'aag/state'
  name: 'aag_sw_rain'
  value_template: '{{ value_json.sw_rain }}'
  icon: "mdi:weather-pouring"
  force_update: true

- platform: mqtt
  state_topic: 'aag/state'
  name: 'aag_light'
  value_template: '{{ value_json.light }}'
  icon: "mdi:lightbulb-on-outline"
  force_update: true

- platform: mqtt
  state_topic: 'aag/state'
  name: 'aag_sw_light'
  value_template: '{{ value_json.sw_light }}'
  icon: "mdi:lightbulb-on-outline"
  force_update: true



- platform: mqtt
  state_topic: 'nhs/state'
  name: 'nhs_tensao_entrada'
  value_template: '{{ value_json.tensao_entrada }}'
  icon: "mdi:current-ac"
  force_update: true

- platform: mqtt
  state_topic: 'nhs/state'
  name: 'nhs_carga'
  value_template: '{{ value_json.carga }}'
  icon: "mdi:gauge-full"
  force_update: true

- platform: mqtt
  state_topic: 'nhs/state'
  name: 'nhs_status'
  value_template: '{{ value_json.status }}'
  icon: "mdi:battery-alert"
  force_update: true



- platform: ror
  host: 192.168.0.157
  port: 1880
  monitored_conditions:
    - safe
    - parked
    - closed
    - mount_parked
    - open
#    - aagsafe

- platform: moon

- platform: systemmonitor
  resources:
    - type: last_boot

