# ui-lovelace.yaml

title: Mastria - Arua

views:
  - cards:

      - type: vertical-stack
        cards:
          - columns: 8
            entities:
              - entity: binary_sensor.aag_light
              - entity: binary_sensor.aag_safe
              - entity: binary_sensor.aag_cloudy
              - entity: binary_sensor.aag_rainy
              - entity: binary_sensor.nhs_onbattery
              - entity: binary_sensor.nhs_critical
              - entity: binary_sensor.obs_alert
            show_icon: true
            show_name: false
            show_state: false
            type: glance
          - entity: camera.allsky
            show_name: false
            show_state: false
            type: picture-entity
          - columns: 4
            entities:
              - entity: binary_sensor.pwr_env
                name: Env
              - entity: binary_sensor.pwr_nodered
                name: Services
              - entity: binary_sensor.pwr_east
                name: East
              - entity: binary_sensor.pwr_west
                name: West
            show_icon: true
            show_name: true
            show_state: false
            type: glance

      - cards:
          - columns: 4
            entities:
              - entity: binary_sensor.mounts_parked
                name: Parked
                icon: 'mdi:telescope'
              - entity: binary_sensor.roof_parked
                name: Locked
              - entity: binary_sensor.roof_closed
                name: Closed
                icon: 'mdi:home-lock'
              - entity: binary_sensor.roof_opened
                name: Opened
                icon: 'mdi:home-lock-open'
            show_icon: true
            show_name: false
            show_state: false
            type: glance
          - entity: camera.observatorio
            show_name: false
            show_state: false
            type: picture-entity
          - cards:
              - entity: switch.system_obs_win
                icon: 'mdi:windows'
                name: LunarScan CAMS
                type: entity-button
              - entity: switch.dehum_front
                icon: 'mdi:weather-windy'
                name: Desumid On/Off
                type: entity-button
              - entity: switch.dehum_back
                icon: 'mdi:weather-windy'
                name: Desumid On/Off
                type: entity-button
              - entity: switch.dehum_auto
                icon: 'mdi:weather-windy'
                name: Desumid Monitor
                type: entity-button
            type: horizontal-stack
          - cards:
              - entity: switch.main
                name: Main
                type: entity-button
              - entity: switch.mounts
                name: Mounts
                icon: 'mdi:telescope'
                type: entity-button
              - entity: switch.indi
                name: Indi
                icon: 'mdi:access-point-network'
                type: entity-button
              - entity: switch.cams
                name: CAMS
                icon: 'mdi:meteor'
                type: entity-button
            type: horizontal-stack
          - cards:
              - entity: switch.roof_lock
                name: Lock
                icon: 'mdi:lock'
                type: entity-button
              - entity: switch.roof_open
                name: Open
                icon: 'mdi:home-lock-open'
                type: entity-button
              - entity: switch.roof_close
                name: Close
                icon: 'mdi:home-lock'
                type: entity-button
              - entity: switch.roof_stop
                name: Stop
                icon: 'mdi:stop'
                type: entity-button
            type: horizontal-stack
          - cards:
              - entity: sensor.hwg_humidity
                graph: line
                name: Umidade
                type: sensor
              - entity: sensor.hwg_temperature
                graph: line
                name: Temperatura
                type: sensor
            type: horizontal-stack
        type: vertical-stack

      - cards:
          - cards:
              - entity: sensor.nhs_tensao_entrada
                max: 150
                min: 0
                name: Entrada (V)
                severity:
                  green: 100
                  red: 0
                  yellow: 135
                theme: default
                type: gauge
                unit: ' '
              - entity: sensor.nhs_carga
                max: 100
                min: 0
                name: Consumo UPS
                severity:
                  green: 0
                  red: 60
                  yellow: 30
                theme: default
                type: gauge
            type: horizontal-stack
          - entities:
              - entity: sensor.moon
              - entity: sun.sun
            type: entities
          - entity: weather.dark_sky
            type: weather-forecast
        type: vertical-stack

    panel: false
    path: default_view
    title: Observatory

  - cards:
      - type: vertical-stack
        cards:
          - entity: camera.garagem
            show_name: false
            show_state: false
            type: picture-entity
          - entity: switch.holof
            icon: 'mdi:track-light'
            name: Holofote
            type: entity-button

    panel: false
    title: Home
