esphome:
  name: esp32a
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  fast_connect: OFF
  networks:
  - ssid: "tucano"
    password: "net.6942"

logger:
  level: Verbose
  
web_server:
  port: 80

ota:

i2c:
  sda: 21
  scl: 22
  scan: True

mqtt:
  broker: 192.168.0.4
  discovery: OFF

status_led:
  pin: GPIO2

text_sensor:
  - platform: template
    name: "IP Address"
    lambda: |-
      std::string str = WiFi.localIP().toString().c_str();
      return { str.c_str() };

sensor:
  - platform: sht3xd
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    address: 0x44
    update_interval: 60s
