# nao atualizar versao o esphome - 1.13.3
# https://github.com/esphome/issues/issues/409
# https://github.com/esphome/issues/issues/455

esphome:
  name: espmini7
  platform: ESP8266
  board: d1_mini

wifi:
  fast_connect: ON
  networks:
  - ssid: "tucano"
    password: "net.6942"

logger:
  level: Verbose

web_server:
  port: 80

ota:

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Sao_Paulo
    servers:
      - 192.168.0.4
    on_time:
      - seconds: 0
        minutes: 0
        hours: 13
        then:
          - switch.toggle: esp_restart

mqtt:
  broker: 192.168.0.4
  discovery: OFF

status_led:
  pin: GPIO2

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
  - platform: template
    name: "Timestamp"
    lambda: |-
      char str[20];
      time_t currTime = id(sntp_time).now().timestamp;
      strftime(str, sizeof(str), "%Y-%m-%d %H:%M:%S", localtime(&currTime));
      return { str };

binary_sensor:
  - platform: status
    name: "MQTT Status"

sensor:
  - platform: wifi_signal
    name: WiFi Signal
  - platform: uptime
    name: Uptime

switch:
  - platform: restart
    id: esp_restart
    name: "Esp Restart"