esphome:
  name: mastria_external_temp
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  networks:
  - ssid: "Toddynho"
    password: "net.6942"
  - ssid: "mm.home"
    password: "net.6942"
  - ssid: "mm.observatorio"
    password: "net.6942"
  - ssid: "Foursys"
    password: "4Sys@2015*"

# Enable logging
logger:

web_server:
  port: 80

mqtt:
  broker: 52.28.141.81
  on_message:
    topic: mastria/external/get
    then:  
    - mqtt.publish:
        topic: mastria/external/temp
        payload: "replay!"

ota:
