# nao atualizar versao o esphome - 1.13.3
# https://github.com/esphome/issues/issues/409
# https://github.com/esphome/issues/issues/455

esphome:
  name: garage_door
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  fast_connect: ON
  networks:
  - ssid: "tucano"
    password: "net.6942"

logger:
  level: Verbose
  
web_server:
  port: 80

ota:

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Sao_Paulo
    servers:
      - 192.168.0.4
    on_time:
      - seconds: 0
        minutes: 0
        hours: 13
        then:
          - switch.toggle: sw_restart

mqtt:
  broker: 192.168.0.4
  discovery: OFF
  on_message:
    topic: garage_door/pulse
    payload: "PULSE"
    qos: 0
    then:
      - output.turn_on: garage_relay
      - delay: 100ms
      - output.turn_off: garage_relay

status_led:
  pin: GPIO2

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
  - platform: template
    name: "Timestamp"
    lambda: |-
      char str[20];
      time_t currTime = id(sntp_time).now().timestamp;
      strftime(str, sizeof(str), "%Y-%m-%d %H:%M:%S", localtime(&currTime));
      return { str };

binary_sensor:
  - platform: status
    name: "MQTT Status"
  - platform: gpio
    name: "Garage Open"
    pin:
      number: GPIO18
#      mode: INPUT
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 1s
      - delayed_off: 1s
  - platform: gpio
    name: "Garage Closed"
    pin:
      number: GPIO19
#      mode: INPUT
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 1s
      - delayed_off: 1s

sensor:
  - platform: wifi_signal
    name: WiFi Signal
  - platform: uptime
    name: Uptime

output:
  - platform: gpio
    pin: GPIO16
    id: garage_relay

switch:
  - platform: restart
    id: sw_restart
    name: "Esp Restart"
