esphome:
  name: obs_roof
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  networks:
  - ssid: "tucano"
    password: "net.6942"

logger:

web_server:
  port: 80

ota:

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Sao_Paulo
    servers:
      - 0.br.pool.ntp.org
      - 1.br.pool.ntp.org
      - 2.br.pool.ntp.org

mqtt:
  broker: 192.168.0.4

### DATA ###

#text_sensor:
#
#  - platform: template
#    id: timestamp
#    name: "Timestamp"
#    lambda: |-
#      char str[20];
#      time_t currTime = id(sntp_time).now().timestamp;
#      strftime(str, sizeof(str), "%Y-%m-%d %H:%M:%S", localtime(&currTime));
#      return { str };
#    update_interval: 60s

switch:

  - platform: gpio
    id: relay
    restore_mode: ALWAYS_OFF
    pin:
      number: GPIO16
      mode: OUTPUT
      inverted: False

  - platform: template
    name: "Roof Move"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay

binary_sensor:

  - platform: gpio
    name: "Mounts Parked"
    pin:
      number: GPIO17
      mode: INPUT
      inverted: False

  - platform: gpio
    name: "Roof Open"
    pin:
      number: GPIO18
      mode: INPUT
      inverted: False

  - platform: gpio
    name: "Roof Closed"
    pin:
      number: GPIO19
      mode: INPUT
      inverted: False

  - platform: gpio
    name: "Weather Safe"
    pin:
      number: GPIO21
      mode: INPUT
      inverted: True
