esphome:
  name: obs_mounts
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  fast_connect: ON
  networks:
  - ssid: "tucano"
    password: "net.6942"

logger:
  level: Verbose
  
web_server:
  port: 80

ota:

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Sao_Paulo
    servers:
      - 192.168.0.4
    on_time:
      - seconds: 0
        minutes: 0
        hours: 13
        then:
          - switch.toggle: sw_restart

mqtt:
  broker: 192.168.0.4
  discovery: OFF

i2c:
  sda: 21
  scl: 22
  scan: True

status_led:
  pin: GPIO2

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
  - platform: template
    name: "Timestamp"
    lambda: |-
      char str[20];
      time_t currTime = id(sntp_time).now().timestamp;
      strftime(str, sizeof(str), "%Y-%m-%d %H:%M:%S", localtime(&currTime));
      return { str };

binary_sensor:
  - platform: status
    name: "MQTT Status"
  - platform: gpio
    name: "East Parked"
    pin:
      number: GPIO16
      mode: INPUT
      inverted: True
    filters:
      - delayed_on: 1s
      - delayed_off: 1s
  - platform: gpio
    name: "West Parked"
    pin:
      number: GPIO18
      mode: INPUT
      inverted: True
    filters:
      - delayed_on: 1s
      - delayed_off: 1s

sensor:
  - platform: wifi_signal
    name: WiFi Signal
  - platform: uptime
    name: Uptime
  - platform: sht3xd
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    address: 0x44
    update_interval: 60s

switch:
  - platform: restart
    id: sw_restart
    name: "Esp Restart"
