# nao atualizar versao o esphome
# https://github.com/esphome/issues/issues/409

esphome:
  name: obs_roof
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  fast_connect: ON
  networks:
  - ssid: "tucano"
    password: "net.6942"

logger:
  level: Verbose
  
web_server:
  port: 80

ota:

mqtt:
  broker: 192.168.0.4
  discovery: OFF
  on_message:
    topic: obs_roof/pulse
    payload: "PULSE"
    qos: 0
    then:
      - output.turn_on: roof_relay
      - delay: 100ms
      - output.turn_off: roof_relay

status_led:
  pin: GPIO2

output:
  - platform: gpio
    pin: GPIO16
    id: roof_relay

switch:

#  - platform: gpio
#    id: relay
#    on_turn_on:
#    - delay: 100ms
#    - switch.turn_off: relay
#    pin:
#      number: GPIO16
#      mode: OUTPUT

binary_sensor:

  - platform: gpio
    name: "Mounts Parked"
    pin:
      number: GPIO17
      mode: INPUT
    filters:
      - delayed_on: 1s
      - delayed_off: 1s

  - platform: gpio
    name: "Roof Open"
    pin:
      number: GPIO18
      mode: INPUT
    filters:
      - delayed_on: 1s
      - delayed_off: 1s

  - platform: gpio
    name: "Roof Closed"
    pin:
      number: GPIO19
      mode: INPUT
    filters:
      - delayed_on: 1s
      - delayed_off: 1s

  - platform: gpio
    name: "Weather Safe"
    pin:
      number: GPIO21
      mode: INPUT
      inverted: True
